import { BufferSet } from './BufferSet';
import { Buffer } from './Buffer';
import { EventEmitter } from './EventEmitter';
import { SelectionManager } from './SelectionManager';
import { CharMeasure } from './utils/CharMeasure';
import { MouseHelper } from './utils/MouseHelper';
import { CustomKeyEventHandler, LinkMatcherHandler, LinkMatcherValidationCallback, CharData, LineData } from './Types';
import { ITerminal, IBrowser, ICharset, ITerminalOptions, IInputHandlingTerminal, ILinkMatcherOptions, IViewport, ILinkifier } from './Interfaces';
import { IRenderer } from './renderer/Interfaces';
export declare class Terminal extends EventEmitter implements ITerminal, IInputHandlingTerminal {
    textarea: HTMLTextAreaElement;
    element: HTMLElement;
    private parent;
    private context;
    private document;
    private body;
    private viewportScrollArea;
    private viewportElement;
    private helperContainer;
    private compositionView;
    private charSizeStyleElement;
    private bellAudioElement;
    private visualBellTimer;
    browser: IBrowser;
    options: ITerminalOptions;
    private colors;
    cursorState: number;
    cursorHidden: boolean;
    convertEol: boolean;
    private sendDataQueue;
    private customKeyEventHandler;
    applicationKeypad: boolean;
    applicationCursor: boolean;
    originMode: boolean;
    insertMode: boolean;
    wraparoundMode: boolean;
    bracketedPasteMode: boolean;
    charset: ICharset;
    gcharset: number;
    glevel: number;
    charsets: ICharset[];
    private decLocator;
    x10Mouse: boolean;
    vt200Mouse: boolean;
    private vt300Mouse;
    normalMouse: boolean;
    mouseEvents: boolean;
    sendFocus: boolean;
    utfMouse: boolean;
    sgrMouse: boolean;
    urxvtMouse: boolean;
    private refreshStart;
    private refreshEnd;
    savedCols: number;
    private readable;
    private writable;
    defAttr: number;
    curAttr: number;
    params: (string | number)[];
    currentParam: string | number;
    prefix: string;
    postfix: string;
    writeBuffer: string[];
    private writeInProgress;
    private xoffSentToCatchUp;
    private writeStopped;
    private surrogateHigh;
    private userScrolling;
    private inputHandler;
    private parser;
    renderer: IRenderer;
    selectionManager: SelectionManager;
    linkifier: ILinkifier;
    buffers: BufferSet;
    viewport: IViewport;
    private compositionHelper;
    charMeasure: CharMeasure;
    private _mouseZoneManager;
    mouseHelper: MouseHelper;
    cols: number;
    rows: number;
    constructor(options?: ITerminalOptions);
    private setup();
    readonly buffer: Buffer;
    eraseAttr(): number;
    focus(): void;
    readonly isFocused: boolean;
    getOption(key: string): any;
    setOption(key: string, value: any): void;
    private _onTextAreaFocus();
    blur(): void;
    private _onTextAreaBlur();
    private initGlobal();
    private bindKeys();
    open(parent: HTMLElement): void;
    private _setTheme(theme);
    static applyAddon(addon: any): void;
    bindMouse(): void;
    destroy(): void;
    refresh(start: number, end: number): void;
    private queueLinkification(start, end);
    showCursor(): void;
    scroll(isWrapped?: boolean): void;
    scrollLines(disp: number, suppressScrollEvent?: boolean): void;
    scrollPages(pageCount: number): void;
    scrollToTop(): void;
    scrollToBottom(): void;
    write(data: string): void;
    private innerWrite();
    writeln(data: string): void;
    attachCustomKeyEventHandler(customKeyEventHandler: CustomKeyEventHandler): void;
    setHypertextLinkHandler(handler: LinkMatcherHandler): void;
    setHypertextValidationCallback(callback: LinkMatcherValidationCallback): void;
    registerLinkMatcher(regex: RegExp, handler: LinkMatcherHandler, options?: ILinkMatcherOptions): number;
    deregisterLinkMatcher(matcherId: number): void;
    hasSelection(): boolean;
    getSelection(): string;
    clearSelection(): void;
    selectAll(): void;
    protected _keyDown(ev: KeyboardEvent): boolean;
    protected _evaluateKeyEscapeSequence(ev: KeyboardEvent): {
        cancel: boolean;
        key: string;
        scrollLines: number;
    };
    setgLevel(g: number): void;
    setgCharset(g: number, charset: ICharset): void;
    protected _keyPress(ev: KeyboardEvent): boolean;
    send(data: string): void;
    bell(): void;
    log(text: string, data?: any): void;
    error(text: string, data?: any): void;
    resize(x: number, y: number): void;
    updateRange(y: number): void;
    maxRange(): void;
    eraseRight(x: number, y: number): void;
    eraseLeft(x: number, y: number): void;
    clear(): void;
    eraseLine(y: number): void;
    blankLine(cur?: boolean, isWrapped?: boolean, cols?: number): LineData;
    ch(cur?: boolean): CharData;
    is(term: string): boolean;
    handler(data: string): void;
    private handleTitle(title);
    index(): void;
    reverseIndex(): void;
    reset(): void;
    private tabSet();
    cancel(ev: Event, force?: boolean): boolean;
    matchColor(r1: number, g1: number, b1: number): number;
    private visualBell();
    private soundBell();
    private syncBellSound();
}
